name: 'ASEv3 Terraform'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - jin/oidc-refactor
    paths:
      - '.github/workflows/LOB-ILB-ASEv3-Terraform.yml'
      - 'reference-implementations/LOB-ILB-ASEv3/terraform/**'
      - '!reference-implementations/LOB-ILB-ASEv3/terraform/**.md'

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/LOB-ILB-ASEv3-Terraform.yml'
      - 'reference-implementations/LOB-ILB-ASEv3/terraform/**'
      - '!reference-implementations/LOB-ILB-ASEv3/terraform/**.md'

permissions:
  id-token: write

env:
  modulePath: 'reference-implementations/LOB-ILB-ASEv3/terraform'
  terraform_version: 1.1.8

jobs:
  validate-plan-and-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@main

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ env.modulePath }}
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      - name: Terraform Validate
        working-directory: ${{ env.modulePath }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.modulePath }}
        continue-on-error: true
        run: |
          terraform plan \
            -var-file="Parameters/uat.tfvars"
      
      - name: Terraform Apply
        working-directory: ${{ env.modulePath }}
        run: |
          terraform apply \
            -auto-approve \
            -var-file="Parameters/uat.tfvars"
